### ISSUE TITLE
Head Models

### ISSUE THREAD

**Issue by Etherad** [Mige5/rs2006sp#20]
The head models for talking now stammer when hdmod is /not/ active, wasnt like that before.

The characters Redbeard Frank and Luthas for the Pirates Treasure quest's head models are tiny and look non-hd when hdmod /is/ active.

**Comment by Mige5** [comment]
You mean theres some sort of issue, even when hdmod isnt active? - also have u tried with smooth anims enabled/disabled?

**Comment by Buogima** [comment]
Yes, thats what i mean, id had smooth anims on in previous versions before HDmod and haven't had this issue, but now both my and npcs head models stammer while talking, and i just checked! The stammering only happens when smooth anims is on and HDmod isnt

Also, while testing i found that the Grand Exchange Clerks also have Non-HDmod head models that are also tiny just like the other two.

**Comment by Mige5** [comment]
I think the stammering issue should now be fixed on next update.

**Comment by Mige5** [comment]
Noticed an issue in smoothing and it would not properly start the anim over, and would kind of twitch a bit, so fixed that.
